name: CI and CD API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17','21']
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK ${{ matrix.java }}
      uses: actions/setup-java@v4.1.0      
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS budgetin;" -uroot -proot
    - name: Unit Test with Maven
      run: mvn test

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  build:
    runs-on: ubuntu-latest
    needs: unit_test
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java JDK 21
      uses: actions/setup-java@v4.1.0      
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Package
      run: mvn package -Dmaven.test.skip=true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: BudgetIn
        path: /home/runner/work/api/api/target/BudgetIn.jar
        overwrite: true

  # deploy:
  #   run-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Download a Artifact
  #     uses: actions/download-artifact@v4.3.1
  #     with:
  #       name: budgetin
